# Generated by Django 4.1 on 2022-09-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_doctor_patient_user_is_doctor_user_is_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
