# Generated by Django 4.1 on 2022-09-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_user_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_pic",
        ),
    ]
